services:
  db:
    image: 'postgres:latest'
    container_name: postgres_sqlalchemy
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_sqlalchemy_data:/var/lib/postgresql/data/
    networks:
      - sqlalchemy_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_sqlalchemy
    ports:
      - "3333:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - pgadmin_sqlalchemy_data:/var/lib/pgadmin
    networks:
      - sqlalchemy_network


volumes:
  postgres_sqlalchemy_data:
    driver: local
  pgadmin_sqlalchemy_data:
    driver: local

networks:
  sqlalchemy_network:
    driver: bridge
